export const SKILLS = [
    "HTML",
    "CSS",
    "Javascript",
    "ReactJs",
    "ThreeJs",
    "Gsap",
    "D3",
    "NextJs",
    "Ionic",
    "NodeJs",
    "ExpressJs",
    "ChatGPT API",
    "Git",
    "Git automation",
    "Figma",
    "Illustrator",
    "Agile",
    "Unity",
    "C#",
    "Wordpress",
    "PHP",
    "SQL",
    "Firebase",
    "MongoDB",
    "Xcode",
    "Android Studio",
    "AWS",
    "Google Cloud Console",
    "SEO",
    "Azure",
]